src/objects/Contract__c.object
<CustomObject>
    <fields>
        <fullName>Doctor__c</fullName>
        <label>Doctor</label>
        <referenceTo>Doctor__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hospital__c</fullName>
        <label>Hospital</label>
        <referenceTo>Hospital__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Salary</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Antigua &amp; Deps</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Brunei</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina</fullName>
                </value>
                <value>
                    <fullName>Burundi</fullName>
                </value>
                <value>
                    <fullName>Cambodia</fullName>
                </value>
                <value>
                    <fullName>Cameroon</fullName>
                </value>
                <value>
                    <fullName>Poland</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_of_birth__c</fullName>
        <label>Date of birth</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>E_mail_Adress__c</fullName>
        <label>E-mail Adress</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Male</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telephone_Number__c</fullName>
        <label>Telephone Number</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Zip_Postal_Code__c</fullName>
        <inlineHelpText>Formats for UK Postal Code:
- AA9A 9AA
- A9A 9AA
- A9 9AA
- A99 9AA
- AA9 9AA
- AA99 9AA</inlineHelpText>
        <label>Zip/Postal Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Hospital__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Antigua &amp; Deps</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Brunei</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina</fullName>
                </value>
                <value>
                    <fullName>Burundi</fullName>
                </value>
                <value>
                    <fullName>Cambodia</fullName>
                </value>
                <value>
                    <fullName>Cameroon</fullName>
                </value>
                <value>
                    <fullName>Poland</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>E_mail_Adress__c</fullName>
        <label>E-mail Adress</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telephone_Number__c</fullName>
        <label>Telephone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Zip_Postal_Code__c</fullName>
        <inlineHelpText>Formats for UK Postal Code:
- AA9A 9AA
- A9A 9AA
- A9 9AA
- A99 9AA
- AA9 9AA
- AA99 9AA</inlineHelpText>
        <label>Zip/Postal Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Hospital</label>
    <nameField>
        <label>Hospital Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hospitals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HM_ContractAddTest.cls
@IsTest
private class HM_ContractAddTest {
    @isTest
    private static void shouldNotInsertWhenOverlappingBeforeExisting() {
        SetupData superData = new SetupData();
        Contract__c newContract = superData.createContract(
                superData.getDoctor(),
                superData.getHospital(),
                Date.newInstance(2021, 6, 10),
                Date.newInstance(2021, 6, 17)
        );

        Test.startTest();
        Database.insert(newContract, false);
        Test.stopTest();

        System.assert(superData.checkIfSelectedContractWasAdd(newContract) == null, 'Overlapping contract was inserted');
    }

    @isTest
    private static void shouldNotInsertWhenOverlappingAfterExisting() {
        SetupData superData = new SetupData();
        Contract__c newContract = superData.createContract(
                superData.getDoctor(),
                superData.getHospital(),
                Date.newInstance(2021, 6, 19),
                Date.newInstance(2021, 6, 26)
        );

        Test.startTest();
        Database.insert(newContract, false);
        Test.stopTest();

        System.assert(superData.checkIfSelectedContractWasAdd(newContract) == null, 'Overlapping contract was inserted');
    }

    @isTest
    private static void shouldNotInsertWhenOverlappingInExisting() {
        SetupData superData = new SetupData();
        Contract__c newContract = superData.createContract(
                superData.getDoctor(),
                superData.getHospital(),
                Date.newInstance(2021, 6, 17),
                Date.newInstance(2021, 6, 19)
        );

        Test.startTest();
        Database.insert(newContract, false);
        Test.stopTest();

        System.assert(superData.checkIfSelectedContractWasAdd(newContract) == null, 'Overlapping contract was inserted');
    }

    @isTest
    private static void shouldNotInsertWhenOverlappingBeforeExistingWithoutEndDate() {
        SetupData superData = new SetupData();
        Contract__c newContract = superData.createContract(
                superData.getDoctor(),
                superData.getHospital(),
                Date.newInstance(2021, 7, 10),
                Date.newInstance(2021, 7, 26)
        );

        Test.startTest();
        Database.insert(newContract, false);
        Test.stopTest();

        System.assert(superData.checkIfSelectedContractWasAdd(newContract) == null, 'Overlapping contract was inserted');
    }

    @isTest
    private static void shouldNotInsertWhenOverlappingInAddedList() {
        SetupData superData = new SetupData();
        List<Contract__c> testContracts = new List<Contract__c>();
        for (Integer i = 0; i < 10; i++) {
            Contract__c newContract = superData.createContract(
                    superData.getDoctor(),
                    superData.getHospital(),
                    Date.newInstance(2021, 7, 10),
                    Date.newInstance(2021, 7, 26)
            );
            testContracts.add(newContract);
        }

        Test.startTest();
        Database.insert(testContracts, false);
        Test.stopTest();

        System.assert(superData.checkIfSelectedContractWasAdd(testContracts[0]) == null, 'Overlapping contract was inserted');
    }

    private class SetupData {
        private Doctor__c doctor;
        private Hospital__c hospital;
        private List<Doctor__c> doctorsList = new List<Doctor__c>();
        private List<Hospital__c> hospitalsList = new List<Hospital__c>();
        Contract__c contract = new Contract__c();
        Contract__c contract2 = new Contract__c();

        public SetupData() {
            createDoctor();
            createHospital();
            contract.Start_Date__c = Date.newInstance(2021, 6, 16);
            contract.End_Date__c = Date.newInstance(2021, 6, 20);
            contract.Hospital__c = hospital.Id;
            contract.Doctor__c = doctor.Id;
            contract.Salary__c = 6543;
            insert contract;
            contract2.Start_Date__c = Date.newInstance(2021, 7, 15);
            contract2.Hospital__c = hospital.Id;
            contract2.Doctor__c = doctor.Id;
            contract2.Salary__c = 6543;
            insert contract2;
        }

        private void createDoctor() {
            doctor = new Doctor__c(
                    Last_Name__c = 'testDoctor112313',
                    Name = 'testDoctor121312321',
                    Gender__c = 'Male',
                    Date_of_birth__c = Date.today(),
                    Telephone_Number__c = '+48123456789',
                    E_mail_Adress__c = 'testt1@mail.com',
                    Country__c = 'Poland',
                    City__c = 'Wwa',
                    Zip_Postal_Code__c = '11 111',
                    Street_Address__c = 'test 1');
            insert doctor;
        }
        private Doctor__c getDoctor() {
//        if (doctorsList != null) {
            return doctor = [
                    SELECT Id
                    FROM Doctor__c
                    Limit 1
            ];
        }
        private void createHospital() {
            hospital = new Hospital__c(
                    Name = 'hospitaltest112312313',
                    Country__c = 'Poland',
                    City__c = 'Wwa',
                    Zip_Postal_Code__c = '11 111',
                    Street_Address__c = 'test 1',
                    Telephone_Number__c = '+48123456789',
                    E_mail_Adress__c = 'testtt1231311@mail.com');
            insert hospital;
        }
        private Hospital__c getHospital() {
            return hospital = [
                    SELECT Id
                    FROM Hospital__c
                    Limit 1
            ];
        }
        private Contract__c createContract(Doctor__c doc, Hospital__c hosp, Date startDate, Date endDate) {
            Contract__c contract = new Contract__c();
            contract.Doctor__c = doc.Id;
            contract.Hospital__c = hosp.Id;
            contract.Start_Date__c = startDate;
            contract.End_Date__c = endDate;
            contract.Salary__c = 1234;
            return contract;
        }
        private Contract__c checkIfSelectedContractWasAdd(Contract__c contract) {
            List<Contract__c> tempContracts = [
                    SELECT Id
                    FROM Contract__c
                    WHERE Start_Date__c = :contract.Start_Date__c AND End_Date__c = :contract.End_Date__c
                    LIMIT 1
            ];
            if (tempContracts.isEmpty()) {
                return null;
            }
            return tempContracts[0];
        }
    }
}