src/objects/Contract__c.object
<CustomObject>
    <fields>
        <fullName>Doctor__c</fullName>
        <label>Doctor</label>
        <referenceTo>Doctor__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hospital__c</fullName>
        <label>Hospital</label>
        <referenceTo>Hospital__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Salary</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Antigua &amp; Deps</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Brunei</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina</fullName>
                </value>
                <value>
                    <fullName>Burundi</fullName>
                </value>
                <value>
                    <fullName>Cambodia</fullName>
                </value>
                <value>
                    <fullName>Cameroon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Hospital__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Antigua &amp; Deps</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Brunei</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina</fullName>
                </value>
                <value>
                    <fullName>Burundi</fullName>
                </value>
                <value>
                    <fullName>Cambodia</fullName>
                </value>
                <value>
                    <fullName>Cameroon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Hospital</label>
    <nameField>
        <label>Hospital Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hospitals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HM_SingleHireModalControler.cls
public with sharing class HM_SingleHireModalControler {
    public List<Hospital__c> hospitals { get; set; }
    public Doctor__c doctor { get; set; }
    public Hospital__c hospital { get; set; }
    public Contract__c contract { get; set; }
    public Boolean renderTable { get; set; }
    public String selectedHospitalId { get; set; }
    public Boolean disableButton { get; set; }
    public Boolean renderHireDates { get; set; }
    public List<element> elements { get; set; }
    public Boolean clearButton { get; set; }
    public Boolean isAdded { get; set; }
    public List<Contract__c> addedContractsList { get; set; }
    public Integer sizeOfAddedDoctors { get; set; }
    private String selectedHospital;

    public HM_SingleHireModalControler(ApexPages.StandardController stdController) {
        this.hospitals = new List<Hospital__c>();
        this.doctor = (Doctor__c) stdController.getRecord();
        this.hospital = new Hospital__c();
        this.contract = new Contract__c();
        this.renderTable = false;
        this.disableButton = false;
        this.renderHireDates = false;
        this.elements = new List<element>();
        this.clearButton = true;
//        this.isAdded = true;
        this.sizeOfAddedDoctors = 0;
    }

    public void searchHospitals() {
        elements.clear();
        String queryString = 'SELECT name, City__c, Country__c FROM Hospital__c ' +
                'WHERE Country__c like \'%' + hospital.Country__c + '%\'';
        if (hospital.Name != null) {
            queryString += 'AND Name like \'%' + hospital.Name + '%\'';
        }
        if (hospital.City__c != null) {
            queryString += 'AND City__c like \'%' + hospital.City__c + '%\'';
        }
        hospitals = Database.query(queryString);

        for (Hospital__c hospital : hospitals) {
            element element = new element();
            element.hospital = hospital;
            element.isSelected = false;
            elements.add(element);
        }
        System.debug(hospitals);
        renderTable = true;
        clearButton = false;
        if (renderHireDates) {
            renderHireDates = false;
        }
        if (contract.Start_Date__c != null || contract.End_Date__c != null || contract.Salary__c != null) {
            contract.Start_Date__c = null;
            contract.End_Date__c = null;
            contract.Salary__c = null;
        }
        if (hospitals.size() < 1) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO, 'Data not found'));
            System.debug('pusta tabela');
//            clearButton = true;
        }
    }

    public void selectHospital() {
        selectedHospitalId = System.currentPageReference().getParameters().get('hospitalId');
        System.debug(selectedHospitalId);
        System.debug(doctor);
        renderHireDates = true;
        for (element element : elements) {
            if (element.hospital.Id == selectedHospitalId) {
                element.isSelected = true;
            } else {
                element.isSelected = false;
            }
        }
    }

    public void hireDoctor() {
        System.debug('elo');
        Hospital__c hospital = [SELECT Id FROM Hospital__c WHERE Id = :selectedHospitalId];
        contract.Doctor__c = doctor.Id;
        contract.Hospital__c = hospital.Id;
        System.debug(contract);
        List<Contract__c> tempContracts = new List<Contract__c>();
        tempContracts.add(contract);
        if (contract.Salary__c <= 0) {
            contract.addError('Salary need to more then 0');
        }
        Database.SaveResult[] srList = Database.insert(tempContracts, false);
        System.debug(srList);
        for (Database.SaveResult saveResult : srList) {
            System.debug(JSON.serializePretty(saveResult));
            if (saveResult.isSuccess()) {
                isAdded = true;
            } else {
                isAdded = false;
            }

        }
        System.debug(isAdded);
    }

    public void clearModal() {
        elements.clear();
        hospitals.clear();
        hospital.Country__c = null;
        hospital.Name = null;
        if (hospital.City__c != null) {
            hospital.City__c = null;
        }
        renderTable = false;
        renderHireDates = false;
        clearButton = true;
        contract.Start_Date__c = null;
//        contract.End_Date__c = null;
        contract.Salary__c = null;
        System.debug('12312312321');
    }

    public class element {
        public Hospital__c hospital { get; set; }
        public Boolean isSelected { get; set; }
    }
}