src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Antigua &amp; Deps</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Brunei</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina</fullName>
                </value>
                <value>
                    <fullName>Burundi</fullName>
                </value>
                <value>
                    <fullName>Cambodia</fullName>
                </value>
                <value>
                    <fullName>Cameroon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_of_birth__c</fullName>
        <label>Date of birth</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>E_mail_Adress__c</fullName>
        <label>E-mail Adress</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telephone_Number__c</fullName>
        <label>Telephone Number</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HM_WebserviceDoctor.cls
global with sharing class HM_WebserviceDoctor {
    webService static List<Doctor__c> getDoctor(){
        List<Doctor__c> doctors = new List<Doctor__c>();
        doctors = [
                SELECT Id, Name, Last_Name__c
                FROM Doctor__c
        ];
        return doctors;
    }

    webService static void createDoctor(String name, String lastName, Integer birthDay, Integer birthMonth, Integer birthYear, String telNumber, String eMail, String country, String city){
        Doctor__c doctor = new Doctor__c();
        doctor.Last_Name__c = lastName;
        doctor.Name = name;
        doctor.Date_of_birth__c = Date.newInstance(birthYear, birthMonth, birthDay);
        doctor.Telephone_Number__c = telNumber;
        doctor.E_mail_Adress__c = eMail;
        doctor.Country__c = country;
        doctor.City__c = city;
        insert doctor;
    }

    webService static void deleteDoctor(String Id){
        Doctor__c doctor = [
                SELECT Id
                FROM Doctor__c
                WHERE Id = :Id
        ];
        delete doctor;
    }
}