src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Antigua &amp; Deps</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Brunei</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina</fullName>
                </value>
                <value>
                    <fullName>Burundi</fullName>
                </value>
                <value>
                    <fullName>Cambodia</fullName>
                </value>
                <value>
                    <fullName>Cameroon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>E_mail_Adress__c</fullName>
        <label>E-mail Adress</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telephone_Number__c</fullName>
        <label>Telephone Number</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HM_DoctorHandler.cls
public with sharing class HM_DoctorHandler {

    @Future(callout = true)
    public static void addDoctorsOnExternalOrg(String serializedDoctors){
        List<Doctor__c> doctors = new List<Doctor__c>();
        HM_RestService restService = new HM_RestService();
        doctors = (List<Doctor__c>) JSON.deserialize(serializedDoctors, List<Doctor__c>.class);
        HM_RestService.HM_DoctorsWrappersList doctorsWrappersList = new HM_RestService.HM_DoctorsWrappersList();
        for (Doctor__c doctor : doctors) {
            HM_RestService.HM_DoctorWrapper doctorWrapper = new HM_RestService.HM_DoctorWrapper();
            doctorWrapper.id = doctor.Id;
            doctorWrapper.name = doctor.Name;
            doctorWrapper.lastName = doctor.Last_Name__c;
            doctorWrapper.email = doctor.E_mail_Adress__c;
            doctorWrapper.telephoneNumber = doctor.Telephone_Number__c;
            doctorWrapper.country = doctor.Country__c;
            doctorsWrappersList.doctorWrappers.add(doctorWrapper);
        }
        System.debug('DS doctorsWrappersList: ' + doctorsWrappersList);

        HM_RestService.HM_ResponseWrapper responseWrapper = restService.addDoctors(doctorsWrappersList);
        List<HM_RestService.HM_DoctorWrapper> wrappersLists = responseWrapper.doctorWrappers;
        for (Doctor__c doctor : doctors) {
            for (HM_RestService.HM_DoctorWrapper hm_doctorWrapper : wrappersLists) {
                if (doctor.Id == hm_doctorWrapper.externalId) {
                    doctor.ExternalId__c = hm_doctorWrapper.id;
                }
            }
        }
        System.debug('Doctors List that is update: ' + doctors);
        update doctors;
        //insert
    }
//    @Future(callout=true)
//    public static void updateDoctorOnExternalOrg(String serializedDoctors){
//        List<Doctor__c> doctors = new List<Doctor__c>();
//        HM_RestService restService = new HM_RestService();
//        doctors = (List<Doctor__c>) JSON.deserialize(serializedDoctors, List<Doctor__c>.class);
//        HM_RestService.HM_DoctorWrapper doctorWrapper = new HM_RestService.HM_DoctorWrapper();
//        for (Doctor__c doctor : doctors) {
//            doctorWrapper.id = doctor.ExternalId__c;
//            doctorWrapper.name = doctor.Name;
//            doctorWrapper.lastName = doctor.Last_Name__c;
//            doctorWrapper.email = doctor.ExternalId__c;
//            doctorWrapper.telephoneNumber = doctor.Telephone_Number__c;
//        }
//        System.debug('wraper to edit on ex org: ' + doctorWrapper);
//        HM_RestService.HM_ResponseWrapper responseWrapper = restService.updateDoctor(doctorWrapper);
//
//    }
}