src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Antigua &amp; Deps</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Brunei</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina</fullName>
                </value>
                <value>
                    <fullName>Burundi</fullName>
                </value>
                <value>
                    <fullName>Cambodia</fullName>
                </value>
                <value>
                    <fullName>Cameroon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>E_mail_Adress__c</fullName>
        <label>E-mail Adress</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HM_DoctorController.cls
public with sharing class HM_DoctorController {
    public List<Doctor__c> doctorsList { get; set; }
    public List<Doctor__c> doctorsListToExport { get; set; }
    public Doctor__c doctor { get; set; }
    public Boolean hideButton { get; set; }
    public String csvString { get; set; }
    Public Integer size { get; set; }
    public List<SelectOption> paginationSizeOptions { get; set; }
    public String stringQuery { get; set; }
    public Integer pageNumberInteger { get; set; }
    public HM_DoctorController() {
        size = 5;
        paginationSizeOptions = new List<SelectOption>();
        paginationSizeOptions.add(new SelectOption('5', '5'));
        paginationSizeOptions.add(new SelectOption('10', '10'));
        paginationSizeOptions.add(new SelectOption('20', '20'));
        paginationSizeOptions.add(new SelectOption('50', '50'));
        paginationSizeOptions.add(new SelectOption('100', '100'));
        doctor = new Doctor__c();
        doctorsList = new List<Doctor__c>();
        doctorsListToExport = new List<Doctor__c>();
        hideButton = true;
        stringQuery = 'select Name, Last_Name__c, E_mail_Adress__c, Country__c ' +
                'from Doctor__c Limit 0';
        csvString = '';
    }
    public ApexPages.StandardSetController setStandardController {
        get {
            if (setStandardController == null) {
                setStandardController = new ApexPages.StandardSetController(Database.getQueryLocator(stringQuery));
            }
            return setStandardController;
        }
        set;
    }
    public void searchDoctors() {
        hideButton = false;
        String country = doctor.Country__c;
        stringQuery = '' +
                'select Name, Last_Name__c, E_mail_Adress__c, Country__c ' +
                'from Doctor__c ' +
                'where Country__c like \'%' + country + '%\'';
        if (doctor.Name != null) {
            stringQuery += ' AND Name like \'%' + doctor.Name + '%\'';
        }
        if (doctor.Last_Name__c != null) {
            stringQuery += ' AND Last_Name__c like \'%' + doctor.Last_Name__c + '%\'';
        }
        if (doctor.E_mail_Adress__c != null) {
            stringQuery += ' AND E_mail_Adress__c like \'%' + doctor.E_mail_Adress__c + '%\'';
        }
        setStandardController = new ApexPages.StandardSetController(Database.getQueryLocator(stringQuery));
        doctorsListToExport = setStandardController.getRecords();
        setStandardController.setPageSize(size);
        pageNumberInteger = 1;
        setStandardController.setPageNumber(pageNumberInteger);
        doctorsList = setStandardController.getRecords();
        if (doctorsList.size() < 1) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO, 'Data not found'));
            hideButton = true;
        }
    }
    public void nextPage() {
        setStandardController.next();
        doctorsList = setStandardController.getRecords();
    }
    public void prevPage() {
        setStandardController.previous();
        doctorsList = setStandardController.getRecords();
    }
    public void firstPage() {
        setStandardController.first();
        doctorsList = setStandardController.getRecords();
    }
    public void lastPage() {
        setStandardController.last();
        doctorsList = setStandardController.getRecords();
    }
    public void refreshPageSize() {
        setStandardController.setPageSize(size);
        doctorsList = setStandardController.getRecords();
    }
    public List<Doctor__c> getDoctors() {
        return (List<Doctor__c>) setStandardController.getRecords();
    }
    public void clear() {
        setStandardController = null;
        doctorsList = null;
        hideButton = true;
        doctorsListToExport = null;
        size = 5;
        doctor.clear();
        stringQuery = 'select Name, Last_Name__c, E_mail_Adress__c, Country__c ' +
                'from Doctor__c Limit 0';
    }
    public PageReference CreateXLS() {
        PageReference pr = new PageReference('/apex/HM_DoctorsListToXls');
        return pr;
    }
    public void createCsvString() {
        csvString = '"First Name","Last Name","E-mail","Country"\r\n';
        for (Doctor__c doc : doctorsListToExport) {
            csvString += '"' + doc.Name + '",';
            csvString += '"' + doc.Last_Name__c + '",';
            csvString += '"' + doc.E_mail_Adress__c + '",';
            csvString += '"' + doc.Country__c + '"\r\n';
        }
    }
    public PageReference CreateCSV() {
        PageReference pr = new PageReference('/apex/HM_DoctorsListToCsv');
        return pr;
    }
}