src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Antigua &amp; Deps</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Brunei</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina</fullName>
                </value>
                <value>
                    <fullName>Burundi</fullName>
                </value>
                <value>
                    <fullName>Cambodia</fullName>
                </value>
                <value>
                    <fullName>Cameroon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_of_birth__c</fullName>
        <label>Date of birth</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>E_mail_Adress__c</fullName>
        <label>E-mail Adress</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telephone_Number__c</fullName>
        <label>Telephone Number</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HM_CsvUploadController.cls
public with sharing class HM_CsvUploadController {
    public Blob csvFileBody { get; set; }
    public string csvAsString { get; set; }
    public String[] csvFileLines { get; set; }
    public List<Doctor__c> doctorsList { get; set; }
    public List<element> listOfElements { get; set; }
    public Boolean simpleTextUnderTable { get; set; }
    public String errorMsg { get; set; }
    public Integer fileSize { get; set; }
    public Boolean isDisable { get; set; }
//    public List<String> csvRecordData {get;set;}
    public HM_CsvUploadController() {
        csvFileLines = new String[]{
        };
        doctorsList = New List<Doctor__c>();
        simpleTextUnderTable = true;
        isDisable = true;
        listOfElements = new List<element>();
//        csvRecordData = new List<String>();
    }

    public void importCSVFile() {
        try {
            System.debug('rozmiar pliku' + fileSize);
//            if (csvFileBody == null) {
//                ApexPages.Message noFile = new ApexPages.Message(ApexPages.severity.ERROR, 'Select File.');
//                ApexPages.addMessage(noFile);
//            }
            csvAsString = csvFileBody.toString();
            csvFileLines = csvAsString.split('\r\n');
            System.debug(JSON.serializePretty(csvFileLines));
            System.debug(csvFileLines[1]);
            listOfElements = new List<element>();
            isDisable = false;

            for (Integer i = 1; i < csvFileLines.size(); i++) {

                string[] csvRecordData = csvFileLines[i].split(',');
                System.debug(csvRecordData);
                element element = new element();
                element.index = i;
                element.doctor.Name = csvRecordData[0];
                element.doctor.Last_Name__c = csvRecordData[1] ;
                element.doctor.E_mail_Adress__c = csvRecordData[2];
                element.doctor.Country__c = csvRecordData[3];
                element.doctor.Date_of_birth__c = Date.parse(csvRecordData[4]);
                element.doctor.Telephone_Number__c = csvRecordData[5];
                element.doctor.City__c = csvRecordData[6];
                listOfElements.add(element);
            }
            System.debug(listOfElements);
            simpleTextUnderTable = false;
            //insert contractsList;
        } catch (Exception e) {
            ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.ERROR, 'Check your CSV file. It must meet all assumptions contained in the manual. If you do not chose file chose it.');
            ApexPages.addMessage(errorMessage);
            if (listOfElements.size() > 0) {
                listOfElements.clear();
            }
            System.debug(e.getMessage());
            System.debug(e.getStackTraceString());
            isDisable = true;
        }
    }

    public void clear() {
        listOfElements.clear();
        simpleTextUnderTable = true;
        isDisable = true;
        csvFileBody = null;
    }

    public void selectAll() {
        for (element element : listOfElements) {
            element.selected = true;
        }
    }

    public void noneSelect() {
        for (element element : listOfElements) {
            element.selected = false;
        }
    }

    public void reverseSelect() {
        for (element element : listOfElements) {
            if (element.selected) {
                element.selected = false;
            } else {
                element.selected = true;
            }
        }
    }

    public void importSelectedDoctors() {
        List<Doctor__c> doctorsToInsert = new List<Doctor__c>();
        List<element> selectedElements = new List<element>();
        for (element element : listOfElements) {
            if (element.selected) {
                doctorsToInsert.add(element.doctor);
                selectedElements.add(element);
            }
        }
        Database.SaveResult[] srList = Database.insert(doctorsToInsert, false);
        for (Integer i = 0; i < srList.size(); i++) {
            Integer index = selectedElements[i].index - 1;
            if (srList[i].isSuccess()) {
                listOfElements[index].status = 'Success';
                listOfElements[index].id = srList[i].getId();
                listOfElements[index].viewLink = true;
            } else {
                List<Database.Error> errors = srList[i].getErrors();
                System.debug(errors);
                errorMsg = '';
                for (Database.Error error : errors) {
                    errorMsg += (error.message + '\n');
                    System.debug(errorMsg);
                }
                listOfElements[index].status = errorMsg;
            }
        }
        System.debug(doctorsToInsert);

    }

    public class element {
        public Doctor__c doctor { get; set; }
        public Boolean selected { get; set; }
        public String status { get; set; }
        public Integer index { get; set; }
        public String id { get; set; }
        public Boolean viewLink { get; set; }

        public element() {
            this.doctor = new Doctor__c();
            this.selected = false;
            this.status = '';
            this.viewLink = false;
        }
    }
}