src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Antigua &amp; Deps</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Brunei</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina</fullName>
                </value>
                <value>
                    <fullName>Burundi</fullName>
                </value>
                <value>
                    <fullName>Cambodia</fullName>
                </value>
                <value>
                    <fullName>Cameroon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>E_mail_Adress__c</fullName>
        <label>E-mail Adress</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telephone_Number__c</fullName>
        <label>Telephone Number</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HM_DoctorSoapService.cls
public with sharing class HM_DoctorSoapService {
    public soapSforceComSchemasClassHmSoupser.HM_SoupService soapService;
    public soapSforceComSchemasClassHmSoupser.SessionHeader_element header;

    public HM_DoctorSoapService() {
        soapService = new soapSforceComSchemasClassHmSoupser.HM_SoupService();
        header = new soapSforceComSchemasClassHmSoupser.SessionHeader_element();
        header.sessionId = getSessionId();
        soapService.SessionHeader = header;
    }

    public String getSessionId() {
        partnerSoapSforceCom.Soap soap = new partnerSoapSforceCom.Soap();
//        HM_IntegrationSetting__c setting = HM_IntegrationSetting__c.getInstance('DoctorsSoapInte');
//        setting.Login;
        HM_Settings__c login =  HM_Settings__c.getInstance('Login');
        HM_Settings__c password =  HM_Settings__c.getInstance('Password');
        partnerSoapSforceCom.LoginResult loginResult = soap.login(login.Value__c, password.Value__c);
        return loginResult.sessionId;
    }

    public List<HM_doctorWrapper> getDoctors(HM_doctorWrapper wrapper) {
        soapSforceComSchemasClassHmSoupser.HM_responseWrapper responseWrapper = new soapSforceComSchemasClassHmSoupser.HM_responseWrapper();
        try {
            responseWrapper = soapService.getDoctors(wrapper.doctorName, wrapper.doctorLastName, wrapper.doctorEmail, wrapper.doctorCountry);
            System.debug('=====================================');
            System.debug(responseWrapper);
        } catch (Exception e) {
        }

        return convertSoapResponseWrappers(responseWrapper.doctorWrappersList);
    }

    public List<HM_doctorWrapper> convertSoapResponseWrappers(List<soapSforceComSchemasClassHmSoupser.HM_doctorWrapper> soapWrappers) {
        List<HM_doctorWrapper> wrappers = new List<HM_doctorWrapper>();
        if (soapWrappers == null) {
            wrappers = null;
            return wrappers;
        }
        for (soapSforceComSchemasClassHmSoupser.HM_doctorWrapper wrapper : soapWrappers) {
            HM_doctorWrapper newWrapper = new HM_doctorWrapper();
            newWrapper.doctorName = wrapper.doctorName;
            newWrapper.doctorLastName = wrapper.doctorLastName;
            newWrapper.doctorEmail = wrapper.doctorEmail;
            newWrapper.doctorCountry = wrapper.doctorCountry;
            newWrapper.doctorId = wrapper.doctorId;
            newWrapper.doctorTelephone = wrapper.doctorTelephone;
            wrappers.add(newWrapper);
        }
        return wrappers;
    }

    public void deleteDoctor(String id) {
        soapSforceComSchemasClassHmSoupser.HM_responseWrapper responseWrapper = new soapSforceComSchemasClassHmSoupser.HM_responseWrapper();
        try {
            responseWrapper = soapService.deleteDoctor(id);
        } catch (Exception e) {}
    }

    public soapSforceComSchemasClassHmSoupser.HM_responseWrapper addDoctor(String name, String lastName, String country, String email, String telephoneNumber) {
        soapSforceComSchemasClassHmSoupser.HM_responseWrapper responseWrapper = new soapSforceComSchemasClassHmSoupser.HM_responseWrapper();
        try {
            responseWrapper = soapService.addDoctor(name, lastName, country, email, telephoneNumber);
        } catch (Exception e) {}
        return responseWrapper;
    }

    public soapSforceComSchemasClassHmSoupser.HM_responseWrapper updateDoctor(String id, String name, String lastName, String country, String email, String telephoneNumber){
        soapSforceComSchemasClassHmSoupser.HM_responseWrapper responseWrapper = new soapSforceComSchemasClassHmSoupser.HM_responseWrapper();
        try {
            responseWrapper = soapService.updateDoctor(id, name, lastName, country, email, telephoneNumber);
        }catch (Exception e){}
        return responseWrapper;
    }

    public class HM_doctorWrapper {
        public String doctorName { get; set; }
        public String doctorLastName { get; set; }
        public String doctorCountry { get; set; }
        public String doctorEmail { get; set; }
        public String doctorId { get; set; }
        public String doctorTelephone { get; set; }

        public HM_doctorWrapper() {
        }

        public HM_doctorWrapper(Doctor__c doctor) {
            this.doctorName = doctor.Name != null ? doctor.Name : '';
            this.doctorLastName = doctor.Last_Name__c;
            this.doctorCountry = doctor.Country__c;
            this.doctorEmail = doctor.E_mail_Adress__c;
            this.doctorId = doctor.Id;
            this.doctorTelephone = doctor.Telephone_Number__c;
        }
    }

    public class HM_responseWrapper {
        public Boolean isSuccess;
        public List<HM_doctorWrapper> doctorWrappersList;
        public String message;
    }
}